controller_manager: # 节点名字
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    fishbot_joint_state_broadcaster: # 会自动扫描所有
      type: joint_state_broadcaster/JointStateBroadcaster # 控制器
    fishbot_effort_controller: # 声明
      type: effort_controllers/JointGroupEffortController
    fishbot_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

# 配置
fishbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

fishbot_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.17
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.032

    # 校准里程计的时候需要这三个参数，设置为1.0说明不进行校准
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    # 表示超过5s钟没收到cmd_vel，机器人会停止
    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true

    # 表示是否使用stamped_vel代替速度命令
    use_stamped_vel: false
    #velocity_rolling_window_size: 10